# Generated by Django 5.1.4 on 2025-01-07 09:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_remove_pairing_cheese_remove_pairing_wine_and_more'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'custom user', 'verbose_name_plural': 'custom users'},
        ),
        migrations.CreateModel(
            name='Favourite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('cheese_id', models.ManyToManyField(to='products.cheese')),
                ('user_id', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
                ('wine_id', models.ManyToManyField(to='products.wine')),
            ],
            options={
                'verbose_name': 'favourite',
                'verbose_name_plural': 'favourites',
            },
        ),
    ]
