# Generated by Django 5.1.4 on 2025-01-31 14:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cheese',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('family', models.CharField(max_length=200)),
                ('type_of_milk', models.CharField(max_length=200)),
                ('region', models.CharField(max_length=200)),
                ('description', models.TextField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name': 'cheese',
                'verbose_name_plural': 'cheeses',
            },
        ),
        migrations.CreateModel(
            name='Wine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('appellation', models.CharField(max_length=200)),
                ('vineyard', models.CharField(max_length=200)),
                ('grape_variety', models.CharField(max_length=200)),
                ('color', models.CharField(max_length=200)),
                ('year', models.DecimalField(decimal_places=0, max_digits=4)),
                ('description', models.TextField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name': 'wine',
                'verbose_name_plural': 'wines',
            },
        ),
        migrations.CreateModel(
            name='Pairing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('cheese', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.cheese')),
                ('wine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.wine')),
            ],
            options={
                'verbose_name': 'pairing',
                'verbose_name_plural': 'pairings',
            },
        ),
    ]
