# Generated by Django 5.1.4 on 2025-01-07 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pairing',
            name='cheese',
        ),
        migrations.RemoveField(
            model_name='pairing',
            name='wine',
        ),
        migrations.AddField(
            model_name='pairing',
            name='cheese_id',
            field=models.ManyToManyField(to='products.cheese'),
        ),
        migrations.AddField(
            model_name='pairing',
            name='wine_id',
            field=models.ManyToManyField(to='products.wine'),
        ),
    ]
