# Generated by Django 5.1.4 on 2025-01-07 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_remove_pairing_cheese_remove_pairing_wine_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wine',
            name='family',
        ),
    ]
