# Generated by Django 5.1.4 on 2025-01-07 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_remove_wine_family'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cheese',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='cheese',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
