# Generated by Django 5.1.4 on 2025-01-07 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_cheese_created_at_alter_cheese_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cheese',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
